### ISSUE TITLE
replace each tab with two whitespaces.

### ISSUE THREAD

**Issue by chengniansun** [uw-pluverse/pluverse-latex-style-guide#22]
https://github.com/uw-pluverse/pluverse-latex-style-guide/blob/d344bd6fe1cc61195443c531e7733480d2658e8c/template/code-lstlisting.tex#L5

**Comment by chengniansun** [comment]
@Cancelll please fix this at your convenience. Thanks.

**Comment by Cancelll** [comment]
This has been fixed by #23

**Comment by chengniansun** [comment]
Thanks.
